server:
  applicationConnectors:
    - type: http
      port: 9091
  adminConnectors: []

blobsConfiguration:
  areBlobsEnabled: true
  store:
    name: AgentStore
    host: localhost
    port: 34001

tracer:
  serviceName: test-blob-client
  enabled: true
  dispatchers:
    - type: logger
      loggerName: dispatcher
    - type: remote
      client:
        type: agent
        host: localhost
        format:
          type: protobuf
