server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors: []

blobs:
  enabled: true
  store:
   name: file

tracer:
  serviceName: blob-server
  enabled: true
  dispatchers:
    - type: logger
      loggerName: dispatcher