server:
  applicationConnectors:
    - type: http
      port: 9091
  adminConnectors: []

serverEndpoint: http://span-blob-example-server:9090/hi

blobsConfiguration:
  areBlobsEnabled: true
  store:
    name: AgentStore
    host: haystack-agent
    port: 34001

tracer:
  serviceName: test-blob-client
  enabled: true
  dispatchers:
    - type: logger
      loggerName: dispatcher
    - type: remote
      client:
        type: agent
        host: haystack-agent
        format:
          type: protobuf
